### ISSUE TITLE
Website was eaten by BuildCraft

### ISSUE THREAD

**Issue by fnuecke** [asiekierka/BuildForgeCraft#20]
http://buildforgecraft.asie.pl/ now is an alias for the new BuildCraft website.

**Comment by asiekierka** [comment]
I am perfectly okay with that.

It's actually a result of a rushed migration to nginx I had to do at 4 AM while being almost entirely asleep. I will fix it.

**Comment by Kubuxu** [comment]
But some info on http://buildforgecraft.asie.pl/ was usefull. Now we were cut off of it.
