### ISSUE TITLE
Blaze powder and rod is used in few recipes.

### ISSUE THREAD

**Issue by Kubuxu** [asiekierka/BuildForgeCraft#3]

**Comment by iTitus** [comment]
- 2 brewing recipes (but they have alternatives)
- H.S. Rail in the Rolling Machine (shaped) (and all child recipes)
- Blazing Electron Tubes in the Thermionic Fabricator
- Blaze Stick in the Assembly Table (=> Portable Laser in the Assembly Table)

**Comment by asiekierka** [comment]
You can now make blaze powder out of gunpowder, and blaze rods out of blaze powder.
