### ISSUE TITLE
Kinetic Duster not working?

### ISSUE THREAD

**Issue by mezz** [asiekierka/BuildForgeCraft#8]
![2015-03-03_01 36 02](https://cloud.githubusercontent.com/assets/916092/6459678/b5271a58-c145-11e4-84b2-ea2b4efec1ad.png)

I finally gathered enough Diamonds to build it, but my Kinetic Duster isn't working.
My coords are 103, 957, the duster setup is just down the stairs to the right.

I'm inputting about 10 RF/t into the laser, so it should only take about 100 seconds to build up the 20,000 RF to create dust. I have burned through half a stack of coal with no results.

@AEnterprise any idea what's wrong?

**Comment by iTitus** [comment]
On my todo list, experienced the same issue myself.

**Comment by AEnterprise** [comment]
it's an odd thing as it looks like it is making progress, i'll take a look later today, it is possible iTitus broke something with his refactor that is in the custom build the server is running as the duster in my test world worked just fine yesterday

**Comment by Kubuxu** [comment]
@mezz there is bug that causes progress to reset with 10RF/t for me it was working with 20RF/t.

**Comment by AEnterprise** [comment]
hmm, just looked through the code and the pr iTitus made, and i don't see what could possibly cause this, i'm thinking more allong the lines of a BC bug here as the code for receiving the energy is sound

"progress += energy"

so that can't be the issue

**Comment by Kubuxu** [comment]
@AEnterprise for me it looked that the progress bar was filling and then resetting to random value. I don't know what is causing it I only observed it.

**Comment by AEnterprise** [comment]
hmm, do some testing when i get home today, if i can't find it then we shall see what heapens once the pr is merged and asie puts the new build on the server

**Comment by Kubuxu** [comment]
Also I think that lasers colours are still based on MJ (scale 0-4) instead of (0-40)

**Comment by iTitus** [comment]
Found the errors. Now this needs to be in my PR...

**Comment by mezz** [comment]
The kinetic duster is working for me now, but it does not output into a chest or pipe, it just shoots it wherever.

**Comment by Vexatos** [comment]
@mezz Did you set the output in the GUI properly?

**Comment by mezz** [comment]
There's a GUI?

**Comment by mezz** [comment]
Ok I build the machine confrabulator and set it in the gui. Works, thanks!

**Comment by AEnterprise** [comment]
glad you got it working, also feel free to ask any more questions you have on the BCA irc channel for the new stuff, things that where already released are documented on the wiki
