### ISSUE TITLE
Barrel-like something.

### ISSUE THREAD

**Issue by Kubuxu** [asiekierka/BuildForgeCraft#9]

**Comment by iTitus** [comment]
Would request JABBA

**Comment by asiekierka** [comment]
@iTitus - JABBA is really meh. Storage Drawers is pretty similar, is that fine with @Kubuxu?

**Comment by Kubuxu** [comment]
I have nothing against it. I am just missing something to store my cobbl'.

**Comment by asiekierka** [comment]
@Kubuxu - then Storage Drawers might feel a tad low (doesn't go to thousands of stacks), but fine.

**Comment by Kubuxu** [comment]
I have nothing against it. I am just missing something to store my cobbl'.
